services:
  # The image name is in the [NAME:TAG] format. This should match what was used to build the Dockerfile 
  image: iriscc:1.0.16
  # DO NOT tamper with this command
  working_dir: /usr/local/iris_cloud_code
  environment:
    - NODE_ENV=production
  command: node bin/www
  volumes:
    # [HOST Path:CONTAINER Path]
    # NOTE: IF NEEDED, ONLY HOST PATH CAN BE CHANGED. DONOT CHANGE THE CONTAINER PATH
    #
    # The following line indicates HOST path which contains the config file required by the event manager
    - /opt/config/cloud_code:/usr/local/iris_cloud_code/configuration
    #
    # The following line indicates HOST path which contains the log files generated the event manager
    - /var/log/iris_cloud_code:/usr/local/iris_cloud_code/log
    #
    # The following line indicates HOST path which contains the certs 
    - /opt/certs:/opt/certs
    #
  ports:
    - 443:443
    - 80:80
